### ISSUE TITLE
doesnt work in leagues

### ISSUE THREAD

**Issue by car357** [Antimated/milestone-levels#3]
not sure why it doesnt pop up in leagues i love this plugin please fix !!!!

**Comment by Antimated** [comment]
Hey sorry for the late reply, just saw that the plugin gained a bit of traction cause of leagues. I actually added a safeguard into this plugin to _**not**_ display notifications in leagues. It uses the same interface as the leagues notifications and there is no way for me to hook in into jagex' notification system. Because if I would allow level-up notifications to be shown when a league notification is shown it would just bug out (trust me I tried this at the start of leagues on my local environment to no avail).

Sorry to dissapoint but I hope you'll still enjoy this plugin on normal worlds!
